# Site settings
title: "less life | grep cc"
email: ccwangzh@sina.com
description: > # this means to ignore newlines until "baseurl:"
  记录生活感悟、iOS开发、Web开发、Mac系统、Linux系统等相关内容 - ccwangzh的个人博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://grep.cc" # the base hostname & protocol for your site
twitter_username: ccwangzh
github_username:  ccwangzh

# Build settings
markdown: kramdown
