name: 'ftqq-send-msg-test'
on: # rebuild any PRs and main branch changes
  push:
    branches: [ "off" ]

jobs:
  send-msg: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: josStorer/get-current-time@v2.1.2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+08:00"
      - uses: easychen/github-action-server-chan@v1.0.0
        with:
          sendkey: ${{ secrets.sendkey }}
          title: "server酱Action更新啦 ${{ steps.current-time.outputs.formattedTime }}"
